- .github/workflows/run_form_tests.yml
- docassemble/MOHUDEvictionProject/data/sources/interviews_run.feature
Added these files:
- tests/features/interviews_run.feature
- .github/workflows/run_form_tests.yml
Want to disable the tests? See documentation for ALKiln tests at https://suffolklitlab.github.io/docassemble-AssemblyLine-documentation/docs/automated_integrated_testing.
> Add ALKiln automated tests

- docassemble/MOHUDEvictionProject/data/questions/court_information.yml
> Check if the county exists in county list before using it to lookup court

- docassemble/MOHUDEvictionProject/data/questions/MOHUDEvictionProject.yml
- docassemble/MOHUDEvictionProject/data/questions/MOHUDMotionToContinue.yml
- docassemble/MOHUDEvictionProject/data/questions/shared.yml
> Remove mandatory blocks from shared.yml

- docassemble/MOHUDEvictionProject/data/questions/MOHUDEvictionProject.yml
- docassemble/MOHUDEvictionProject/data/questions/MOHUDMotionToContinue.yml
- docassemble/MOHUDEvictionProject/data/questions/court_information.yml
- docassemble/MOHUDEvictionProject/data/questions/defense_logic.yml
- docassemble/MOHUDEvictionProject/data/questions/eviction_motion_to_continue.yml
- docassemble/MOHUDEvictionProject/data/questions/shared.yml
Getting the interview order in place required changing a fair amount of code in different parts of the interview so this PR is larger than ideal.
Fix #305 
Fix #310 
Fix #311 
Fix #171 
Fix #292 
Fix #314
> Signposts progress

- docassemble/MOHUDEvictionProject/data/questions/MOHUDEvictionProject.yml
- docassemble/MOHUDEvictionProject/data/questions/MOHUDMotionToContinue.yml
- docassemble/MOHUDEvictionProject/data/questions/court_information.yml
- docassemble/MOHUDEvictionProject/data/questions/shared.yml
1. Remove `if` statement on blocks, combine questions
2. Move other party attorney gather to complete statement
Of note, on line 147 in court info yml I did not change "case type" to "nature of suit" (two questions I combined had different things). I did not notice until merge on github.
Fix #308
> Remove if statement blocks

- docassemble/MOHUDEvictionProject/data/questions/autoterms.yml
- Fix #375 
- Update #374 (no attorney logic yet)
- Will complete #344 in a different PR
> Plain language review of current terms

- docassemble/MOHUDEvictionProject/data/questions/MOHUDEvictionProject.yml
- docassemble/MOHUDEvictionProject/data/questions/court_information.yml
- docassemble/MOHUDEvictionProject/data/questions/shared.yml
> Updates to attorney service and Landlord name

- docassemble/MOHUDEvictionProject/data/questions/MOHUDEvictionProject.yml
> Small language change: then --> than

- docassemble/MOHUDEvictionProject/data/questions/MOHUDEvictionProject.yml
- docassemble/MOHUDEvictionProject/data/questions/shared.yml
- Updates to #378 
- Still unlear how to  Let people know the deadline to file their answer, will ask Terry
- Using `county_dictionary[trial_court.county][' court_address_and_operating_hours']` for now to reference court info but updating to AL model would make it much more flexible (See #392). Currently the formatting is just a single uncontrollable line (see screenshot attached)
> Update download screen

- docassemble/MOHUDEvictionProject/data/questions/feedback.yml
> Add MOTenantHelp Resources link to feedback form

- docassemble/MOHUDEvictionProject/data/questions/defense_logic.yml
>  Remove follow up references to "signing" written lease 

- docassemble/MOHUDEvictionProject/data/questions/MOHUDEvictionProject.yml
- docassemble/MOHUDEvictionProject/data/questions/MOHUDMotionToContinue.yml
- docassemble/MOHUDEvictionProject/data/questions/autoterms.yml
- docassemble/MOHUDEvictionProject/data/questions/court_information.yml
- docassemble/MOHUDEvictionProject/data/questions/defense_logic.yml
- docassemble/MOHUDEvictionProject/data/questions/eviction_motion_to_continue.yml
- docassemble/MOHUDEvictionProject/data/questions/motion_tester.yml
- docassemble/MOHUDEvictionProject/data/questions/questions_draft.yml
- docassemble/MOHUDEvictionProject/data/questions/shared.yml
> Glossaryupdates

- docassemble/MOHUDEvictionProject/data/questions/defense_logic.yml
> Update rental summary language

- docassemble/MOHUDEvictionProject/data/questions/shared.yml
> add_feedback_widget

- docassemble/MOHUDEvictionProject/data/questions/defense_logic.yml
> payment attempts

- docassemble/MOHUDEvictionProject/data/questions/MOHUDEvictionProject.yml
- docassemble/MOHUDEvictionProject/data/questions/MOHUDMotionToContinue.yml
> fix_posting_logic

- docassemble/MOHUDEvictionProject/data/questions/court_information.yml
> Move examples in id: case type from summons to help button #396

- docassemble/MOHUDEvictionProject/data/questions/MOHUDMotionToContinue.yml
Fixed sections that was jumping around by moving up using case net
Also fixed problem with person_type on review screen
close #461  
> changed order of sections to prevent jumping around in motion to continue

- docassemble/MOHUDEvictionProject/data/questions/file_a_motion.yml
Fixed filename on next steps document
Also fixed the person_type bug for motion tester
close #554 
> fixed motion helper next steps filename

- docassemble/MOHUDEvictionProject/data/questions/MOHUDMotionToContinue.yml
- docassemble/MOHUDEvictionProject/data/questions/shared.yml
Made requested language changes to time estimate for motion to continue and case.net instructions
close #376 
close #107 
> changed language for two issues

- docassemble/MOHUDEvictionProject/data/questions/court_information.yml
- docassemble/MOHUDEvictionProject/data/questions/shared.yml
I changed the formatting of county_dictionary to allow more information about courts and to provide the right information when there are more than two courts in one county.  I added to the court name to ask for a location name if it is appropriate, and I added code to update trial_court to the appropriate court to use trial court and specific attributes on the download page.
close #440 
close #542 
> fixed formatting of court address and added question about which court

- docassemble/MOHUDEvictionProject/data/questions/court_information.yml
There was a dead link in the county look-up. Replaced with a working link and updated phrasing to ensure no one thought they would be looking at a map.
Fixed #586 
> Update county search link

- docassemble/MOHUDEvictionProject/data/questions/MOHUDEvictionProject.yml
- docassemble/MOHUDEvictionProject/data/questions/MOHUDMotionToContinue.yml
- docassemble/MOHUDEvictionProject/data/questions/al_reminders.yml
- docassemble/MOHUDEvictionProject/data/questions/autoterms.yml
- docassemble/MOHUDEvictionProject/data/questions/court_information.yml
- docassemble/MOHUDEvictionProject/data/questions/defense_logic.yml
- docassemble/MOHUDEvictionProject/data/questions/discovery.yml
- docassemble/MOHUDEvictionProject/data/questions/feedback.yml
- docassemble/MOHUDEvictionProject/data/questions/file_a_motion.yml
- docassemble/MOHUDEvictionProject/data/questions/information_collected.yml
- docassemble/MOHUDEvictionProject/data/questions/legalaidlocator.yml
- docassemble/MOHUDEvictionProject/data/questions/reminder.yml
- docassemble/MOHUDEvictionProject/data/questions/review.yml
- docassemble/MOHUDEvictionProject/data/questions/shared.yml
- All blocks now have an id.
- Removed reminders because Case.net provides more thorough options.
- Updated steps on intro pages so they are clearer for users.
- Added Case.net instructions for judgment_date.
Fixed #366, Fixed #610, Fixed #627, Fixed #628, Fixed #629, Fixed #630 
> Language and id updates

- docassemble/MOHUDEvictionProject/data/questions/court_information.yml
- docassemble/MOHUDEvictionProject/data/questions/intake.yml
> Update per LSEM feedback, fix #653
